// UI Strings
export const SITE_NAME = "Ideal Photography";
export const TAGLINE = "Your premier destination for professional photography equipment rentals.";
// Mock data for development and testing
export const MOCK_HISTORY_ITEMS = [
    // Rental items
    {
        id: "rental_1",
        type: "rental",
        ref: "BK-R001",
        title: "Sony A7 III Camera Kit",
        date: "2024-01-15T10:00:00Z",
        time: "10:00 AM",
        status: "completed",
        total: 45000,
        currency: "NGN",
        location: "Ideas Media Company, Ikeja",
        items: [
            {
                name: "Sony A7 III Camera",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                unitPrice: 25000,
                subtotal: 25000,
                rentalPeriod: {
                    startDate: "2024-01-15",
                    endDate: "2024-01-17",
                    duration: "3 days",
                },
            },
            {
                name: "50mm f/1.8 Lens",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                unitPrice: 15000,
                subtotal: 15000,
                rentalPeriod: {
                    startDate: "2024-01-15",
                    endDate: "2024-01-17",
                    duration: "3 days",
                },
            },
            {
                name: "Camera Bag",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                unitPrice: 5000,
                subtotal: 5000,
                rentalPeriod: {
                    startDate: "2024-01-15",
                    endDate: "2024-01-17",
                    duration: "3 days",
                },
            },
        ],
        createdAt: "2024-01-12T08:30:00Z",
        updatedAt: "2024-01-17T18:00:00Z",
        receipt: { generated: true, url: "/receipts/rental_1.pdf" },
    },
    {
        id: "rental_2",
        type: "rental",
        ref: "BK-R002",
        title: "Professional Lighting Setup",
        date: "2024-01-20T09:00:00Z",
        time: "09:00 AM",
        status: "confirmed",
        total: 35000,
        currency: "NGN",
        location: "Ideas Media Company, Ikeja",
        items: [
            {
                name: "Godox Studio Light Kit",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                unitPrice: 20000,
                subtotal: 20000,
                rentalPeriod: {
                    startDate: "2024-01-20",
                    endDate: "2024-01-22",
                    duration: "3 days",
                },
            },
            {
                name: "Light Stands (Set of 3)",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                unitPrice: 10000,
                subtotal: 10000,
                rentalPeriod: {
                    startDate: "2024-01-20",
                    endDate: "2024-01-22",
                    duration: "3 days",
                },
            },
            {
                name: "Backdrop Stand",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                unitPrice: 5000,
                subtotal: 5000,
                rentalPeriod: {
                    startDate: "2024-01-20",
                    endDate: "2024-01-22",
                    duration: "3 days",
                },
            },
        ],
        createdAt: "2024-01-18T14:20:00Z",
        updatedAt: "2024-01-18T14:20:00Z",
    },

    // Photoshoot items
    {
        id: "photoshoot_1",
        type: "photoshoot",
        ref: "BK-P001",
        title: "Portrait Photography Session",
        date: "2024-01-10T14:00:00Z",
        time: "2:00 PM",
        status: "completed",
        total: 80000,
        currency: "NGN",
        location: "Ideas Media Studio, Victoria Island",
        items: [
            {
                name: "Portrait Photography Session",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                duration: "2 hours",
                serviceDetails: {
                    date: "2024-01-10",
                    time: "2:00 PM",
                    duration: "2 hours",
                    specialRequests: "Professional headshots for LinkedIn",
                },
            },
        ],
        createdAt: "2024-01-08T11:00:00Z",
        updatedAt: "2024-01-10T16:30:00Z",
        receipt: { generated: true, url: "/receipts/photoshoot_1.pdf" },
    },
    {
        id: "photoshoot_2",
        type: "photoshoot",
        ref: "BK-P002",
        title: "Wedding Photography Package",
        date: "2024-01-25T10:00:00Z",
        time: "10:00 AM",
        status: "confirmed",
        total: 250000,
        currency: "NGN",
        location: "Federal Palace Hotel, Victoria Island",
        items: [
            {
                name: "Full Wedding Photography",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                duration: "8 hours",
                serviceDetails: {
                    date: "2024-01-25",
                    time: "10:00 AM",
                    duration: "8 hours",
                    specialRequests: "Traditional and white wedding coverage",
                },
            },
        ],
        createdAt: "2024-01-15T09:45:00Z",
        updatedAt: "2024-01-15T09:45:00Z",
    },

    // Makeover items
    {
        id: "makeover_1",
        type: "makeover",
        ref: "BK-M001",
        title: "Bridal Makeover Package",
        date: "2024-01-08T08:00:00Z",
        time: "8:00 AM",
        status: "completed",
        total: 120000,
        currency: "NGN",
        location: "Ideas Beauty Studio, Ikeja",
        items: [
            {
                name: "Bridal Makeup & Hair",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                duration: "4 hours",
                serviceDetails: {
                    date: "2024-01-08",
                    time: "8:00 AM",
                    duration: "4 hours",
                    specialRequests: "Traditional Nigerian bride look",
                },
            },
        ],
        createdAt: "2024-01-05T16:30:00Z",
        updatedAt: "2024-01-08T12:30:00Z",
        receipt: { generated: true, url: "/receipts/makeover_1.pdf" },
    },
    {
        id: "makeover_2",
        type: "makeover",
        ref: "BK-M002",
        title: "Professional Headshot Makeover",
        date: "2024-01-22T11:00:00Z",
        time: "11:00 AM",
        status: "pending",
        total: 45000,
        currency: "NGN",
        location: "Ideas Beauty Studio, Ikeja",
        items: [
            {
                name: "Professional Makeup",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                duration: "2 hours",
                serviceDetails: {
                    date: "2024-01-22",
                    time: "11:00 AM",
                    duration: "2 hours",
                    specialRequests: "Natural corporate look",
                },
            },
        ],
        createdAt: "2024-01-19T13:15:00Z",
        updatedAt: "2024-01-19T13:15:00Z",
    },

    // Shop items
    {
        id: "shop_1",
        type: "shop",
        ref: "ORD-S001",
        title: "Photography Accessories",
        date: "2024-01-12T15:30:00Z",
        time: null,
        status: "delivered",
        total: 25000,
        currency: "NGN",
        location: "Delivery Address: 123 Mainland Street, Lagos",
        items: [
            {
                name: "Memory Card 64GB",
                quantity: 2,
                thumb: "/api/placeholder/100/100",
                unitPrice: 8000,
                subtotal: 16000,
            },
            {
                name: "Camera Cleaning Kit",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                unitPrice: 5000,
                subtotal: 5000,
            },
            {
                name: "Lens Filter UV 67mm",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                unitPrice: 4000,
                subtotal: 4000,
            },
        ],
        createdAt: "2024-01-12T15:30:00Z",
        updatedAt: "2024-01-14T10:45:00Z",
        receipt: { generated: true, url: "/receipts/shop_1.pdf" },
    },
    {
        id: "shop_2",
        type: "shop",
        ref: "ORD-S002",
        title: "Studio Essentials",
        date: "2024-01-18T12:00:00Z",
        time: null,
        status: "processing",
        total: 15000,
        currency: "NGN",
        location: "Pickup: Ideas Media Company, Ikeja",
        items: [
            {
                name: "Backdrop Paper Roll - White",
                quantity: 2,
                thumb: "/api/placeholder/100/100",
                unitPrice: 6000,
                subtotal: 12000,
            },
            {
                name: "Gaffer Tape",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                unitPrice: 3000,
                subtotal: 3000,
            },
        ],
        createdAt: "2024-01-18T12:00:00Z",
        updatedAt: "2024-01-18T14:30:00Z",
    },

    // Additional items for variety
    {
        id: "rental_3",
        type: "rental",
        ref: "BK-R003",
        title: "Video Equipment Package",
        date: "2024-01-05T13:00:00Z",
        time: "1:00 PM",
        status: "returned",
        total: 85000,
        currency: "NGN",
        location: "Ideas Media Company, Ikeja",
        items: [
            {
                name: "Sony FX3 Cinema Camera",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                unitPrice: 50000,
                subtotal: 50000,
                rentalPeriod: {
                    startDate: "2024-01-05",
                    endDate: "2024-01-08",
                    duration: "4 days",
                },
            },
            {
                name: "Wireless Mic System",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                unitPrice: 20000,
                subtotal: 20000,
                rentalPeriod: {
                    startDate: "2024-01-05",
                    endDate: "2024-01-08",
                    duration: "4 days",
                },
            },
            {
                name: "Tripod - Carbon Fiber",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                unitPrice: 15000,
                subtotal: 15000,
                rentalPeriod: {
                    startDate: "2024-01-05",
                    endDate: "2024-01-08",
                    duration: "4 days",
                },
            },
        ],
        createdAt: "2024-01-03T10:00:00Z",
        updatedAt: "2024-01-08T17:30:00Z",
        receipt: { generated: true, url: "/receipts/rental_3.pdf" },
    },
    {
        id: "photoshoot_3",
        type: "photoshoot",
        ref: "BK-P003",
        title: "Product Photography",
        date: "2023-12-28T11:00:00Z",
        time: "11:00 AM",
        status: "completed",
        total: 65000,
        currency: "NGN",
        location: "Ideas Media Studio, Victoria Island",
        items: [
            {
                name: "Product Photography Session",
                quantity: 1,
                thumb: "/api/placeholder/100/100",
                duration: "3 hours",
                serviceDetails: {
                    date: "2023-12-28",
                    time: "11:00 AM",
                    duration: "3 hours",
                    specialRequests: "White background, 20 products",
                },
            },
        ],
        createdAt: "2023-12-26T09:20:00Z",
        updatedAt: "2023-12-28T14:45:00Z",
        receipt: { generated: true, url: "/receipts/photoshoot_3.pdf" },
    },
];
// Mock stats calculation
export const calculateMockStats = (items) => {
    const stats = {
        total: items.length,
        byType: {
            rental: 0,
            photoshoot: 0,
            makeover: 0,
            shop: 0,
        },
        byStatus: {
            completed: 0,
            upcoming: 0,
            cancelled: 0,
            refunded: 0,
        },
        totalSpent: 0,
        avgOrderValue: 0,
    };

    items.forEach((item) => {
        // Count by type
        if (stats.byType[item.type] !== undefined) {
            stats.byType[item.type]++;
        }

        // Count by status category
        if (["completed", "delivered", "returned"].includes(item.status)) {
            stats.byStatus.completed++;
        } else if (
            ["confirmed", "pending", "processing", "ready_for_pickup", "in_progress"].includes(
                item.status
            )
        ) {
            stats.byStatus.upcoming++;
        } else if (item.status === "cancelled") {
            stats.byStatus.cancelled++;
        } else if (item.status === "refunded") {
            stats.byStatus.refunded++;
        }

        // Calculate totals
        if (item.total && ["completed", "delivered", "in_progress", "returned"].includes(item.status)) {
            stats.totalSpent += item.total;
        }
    });

    // Calculate average
    const completedOrders = stats.byStatus.completed;
    stats.avgOrderValue = completedOrders > 0 ? stats.totalSpent / completedOrders : 0;

    return stats;
};
// Dummy product data for ProductList page
export const DUMMY_PRODUCTS = [
    {
        id: 1,
        title: "Canon EOS 90D DSLR Kit",
        description: "Compact and powerful DSLR kit perfect for event and portrait photography. Includes lens + carry case.",
        image: "/images/idealPhotography-product-card-equipment-1.jpg",
        hoverImage: "/images/idealPhotography-product-card-equipment-5.jpg",
        discountPercent: 17,
        price: 2499.99,
        originalPrice: 2999.99,
        stock: 12,
        rating: 4,
        reviewCount: 134,
        discountValidUntil: "July 30",
        category: "cameras",
        tags: ["dslr", "canon", "kit", "professional"],
        createdAt: "2024-01-15",
    },
    {
        id: 2,
        title: "Nikon D850",
        description: "High-resolution full-frame DSLR for professionals.",
        image: "/images/idealPhotography-product-card-equipment-2.jpg",
        hoverImage: "/images/idealPhotography-product-card-equipment-3.jpg",
        discountPercent: 10,
        price: 3499.99,
        originalPrice: 3899.99,
        stock: 7,
        rating: 5,
        reviewCount: 89,
        discountValidUntil: "Nov 30",
        category: "cameras",
        tags: ["dslr", "nikon", "full-frame", "professional"],
        createdAt: "2024-01-10",
    },
    {
        id: 3,
        title: "Canon RF 50mm f/1.8 STM Lens",
        description: "A compact, lightweight prime lens for Canon RF-mount cameras. Perfect for portraits and low-light photography.",
        image: "/images/idealPhotography-product-card-equipment-6.jpg",
        hoverImage: "/images/idealPhotography-product-card-equipment-2.jpg",
        discountPercent: 5,
        price: 129.99,
        originalPrice: 149.99,
        stock: 15,
        rating: 4,
        reviewCount: 58,
        discountValidUntil: "Feb 30",
        category: "lenses",
        tags: ["canon", "prime", "portrait", "low-light"],
        createdAt: "2024-01-05",
    },
    {
        id: 4,
        title: "Godox AD200Pro Flash",
        description: "Portable, powerful flash for on-location shoots. TTL, HSS, and multiple light modifiers supported.",
        image: "/images/idealPhotography-product-card-equipment-5.jpg",
        hoverImage: "/images/idealPhotography-product-card-equipment-4.jpg",
        discountPercent: 8,
        price: 299.99,
        originalPrice: 324.99,
        stock: 0,
        rating: 5,
        reviewCount: 33,
        discountValidUntil: "Mar 30",
        category: "lighting",
        tags: ["flash", "godox", "ttl", "hss", "portable"],
        createdAt: "2024-01-12",
    },
    {
        id: 5,
        title: "Canon EOS 90D DSLR Kit",
        description: "Compact and powerful DSLR kit perfect for event and portrait photography. Includes lens + carry case.",
        image: "/images/idealPhotography-product-card-equipment-1.jpg",
        hoverImage: "/images/idealPhotography-product-card-equipment-2.jpg",
        discountPercent: 17,
        price: 2499.99,
        originalPrice: 2999.99,
        stock: 12,
        rating: 4,
        reviewCount: 134,
        discountValidUntil: "July 30",
        category: "cameras",
        tags: ["dslr", "canon", "kit", "professional"],
        createdAt: "2024-01-15",
    },
    {
        id: 6,
        title: "Canon EOS 90D DSLR Kit",
        description: "Compact and powerful DSLR kit perfect for event and portrait photography. Includes lens + carry case.",
        image: "/images/idealPhotography-product-card-equipment-5.jpg",
        hoverImage: "/images/idealPhotography-product-card-equipment-3.jpg",
        discountPercent: 17,
        price: 2499.99,
        originalPrice: 2999.99,
        stock: 12,
        rating: 4,
        reviewCount: 134,
        discountValidUntil: "July 30",
        category: "cameras",
        tags: ["dslr", "canon", "kit", "professional"],
        createdAt: "2024-01-15",
    },
    {
        id: 7,
        title: "Sony Alpha a7 III Mirrorless",
        description: "Versatile full-frame mirrorless camera with excellent autofocus and low-light performance.",
        image: "/images/idealPhotography-product-card-equipment-1.jpg",
        hoverImage: "/images/idealPhotography-product-card-equipment-2.jpg",
        discountPercent: 12,
        price: 2199.99,
        originalPrice: 2499.99,
        stock: 9,
        rating: 5,
        reviewCount: 102,
        discountValidUntil: "Aug 15",
        category: "cameras",
        tags: ["mirrorless", "sony", "full-frame", "video"],
        createdAt: "2024-01-18",
    },
    {
        id: 8,
        title: "Sigma 24-70mm f/2.8 DG DN Art Lens",
        description: "High-performance standard zoom lens for Sony E-mount. Ideal for events, portraits, and landscapes.",
        image: "/images/idealPhotography-product-card-equipment-1.jpg",
        hoverImage: "/images/idealPhotography-product-card-equipment-2.jpg",
        discountPercent: 7,
        price: 1099.99,
        originalPrice: 1199.99,
        stock: 6,
        rating: 4,
        reviewCount: 41,
        discountValidUntil: "Sep 10",
        category: "lenses",
        tags: ["sigma", "zoom", "sony", "event"],
        createdAt: "2024-01-20",
    },
    {
        id: 9,
        title: "Manfrotto 190X Tripod Kit",
        description: "Sturdy, lightweight tripod with ball head. Perfect for studio and outdoor shoots.",
        image: "/images/idealPhotography-product-card-equipment-1.jpg",
        hoverImage: "/images/idealPhotography-product-card-equipment-2.jpg",
        discountPercent: 15,
        price: 179.99,
        originalPrice: 209.99,
        stock: 18,
        rating: 4,
        reviewCount: 27,
        discountValidUntil: "Oct 5",
        category: "accessories",
        tags: ["tripod", "manfrotto", "stabilizer", "outdoor"],
        createdAt: "2024-01-22",
    },
    // TODO: Add more dummy products or fetch from server when available
];

// Our Services (for homepage and footer)
export const OUR_SERVICES = [
    {
        title: "Equipment Rentals",
        subtitle: "Rent cameras, lenses, lighting, and more from top and notable brands.",
        href: "/equipment",
        iconType: "camera",
        gifUrl: "/GIFs/idealPhotography-feature-card-equipment.gif",
        imageUrl: "/images/idealPhotography-feature-card-equipment.png",
    },
    {
        title: "Makeover Sessions",
        subtitle: "Book professional makeover and styling sessions.",
        href: "/makeover",
        iconType: "makeover",
        gifUrl: "/GIFs/idealPhotography-feature-card-makeover.gif",
        imageUrl: "/images/idealPhotography-feature-card-makeover.jpg",
    },
    {
        title: "Photoshoot Bookings",
        subtitle: "Reserve studio or outdoor photoshoot sessions.",
        href: "/photoshoot",
        iconType: "photoshoot",
        gifUrl: "/GIFs/idealPhotography-feature-card-photoshoot.gif",
        imageUrl: "/images/idealPhotography-feature-card-photoshoot.png",
    },
    {
        title: "Event Coverage",
        subtitle: "Hire our team for weddings, parties, and corporate events.",
        href: "/events",
        iconType: "users",
        gifUrl: "/GIFs/idealPhotography-feature-card-event.gif",
        imageUrl: "/images/idealPhotography-feature-card-event.png",
    },
    {
        title: "Mini Mart",
        subtitle: "Shop photography accessories, prints, and more.",
        href: "/mini-mart",
        iconType: "shop",
        gifUrl: "/GIFs/idealPhotography-feature-card-shop.gif",
        imageUrl: "/images/idealPhotography-feature-card-mini-shop.jpg",
    },
];

// Why Choose Us (for homepage)
export const WHY_CHOOSE_US = [
    {
        title: "Premium Equipment",
        description: "Access to the latest cameras, lenses, and accessories from top brands like Canon, Sony, Nikon, and more.",
        iconType: "camera",
    },
    {
        title: "Flexible Rental Periods",
        description: "Rent for a day, week, or month. We offer competitive rates for both short-term and long-term rentals.",
        iconType: "time",
    },
    {
        title: "Expert Support",
        description: "Our photography experts are available 24/7 to help you choose the right equipment and provide technical support.",
        iconType: "support",
    },
    {
        title: "Easy Booking",
        description: "Simple online booking system with real-time availability. Reserve your gear in just a few clicks.",
        iconType: "photoshoot",
    },
    {
        title: "Quality Guaranteed",
        description: "All equipment is professionally maintained, tested, and cleaned before every rental to ensure peak performance.",
        iconType: "quality",
    },
    {
        title: "Insured Equipment",
        description: "All rentals include comprehensive insurance coverage for peace of mind during your creative projects.",
        iconType: "secure",
    },
];
// Enhanced makeover services data
export const MAKEOVERS = [
    {
        id: "bridal",
        title: "Bridal Glam",
        description: "For your special day",
        price: 50000,
        originalPrice: 65000,
        discountPercent: 23,
        category: "bridal",
        duration: "long",
        createdAt: "2024-01-15",
        tags: ["bridal", "wedding", "glamorous"],
        imageUrl: "/images/idealPhotography-product-card-makeover-1.png",
        rating: 4.8,
        reviewCount: 127,
    },
    {
        id: "matte",
        title: "Matte Finish",
        description: "Smooth & bold",
        price: 30000,
        originalPrice: 35000,
        discountPercent: 14,
        category: "casual",
        duration: "short",
        createdAt: "2024-01-10",
        tags: ["matte", "casual", "natural"],
        imageUrl: "/images/idealPhotography-product-card-makeover-2.png",
        rating: 4.5,
        reviewCount: 89,
    },
    {
        id: "traditional",
        title: "Traditional Look",
        description: "Cultural richness",
        price: 40000,
        originalPrice: 45000,
        discountPercent: 11,
        category: "traditional",
        duration: "medium",
        createdAt: "2024-01-20",
        tags: ["traditional", "cultural", "heritage"],
        imageUrl: "/images/idealPhotography-product-card-makeover-1.png",
        rating: 4.7,
        reviewCount: 156,
    },
    {
        id: "party",
        title: "Party Glam",
        description: "Perfect for celebrations",
        price: 35000,
        originalPrice: 40000,
        discountPercent: 13,
        category: "party",
        duration: "medium",
        createdAt: "2024-01-12",
        tags: ["party", "celebration", "glamorous"],
        imageUrl: "/images/idealPhotography-product-card-makeover-2.png",
        rating: 4.6,
        reviewCount: 203,
    },
    {
        id: "editorial",
        title: "Editorial Chic",
        description: "High-fashion, magazine-style makeover for bold statements.",
        price: 45000,
        originalPrice: 50000,
        discountPercent: 10,
        category: "editorial",
        duration: "long",
        createdAt: "2024-01-25",
        tags: ["editorial", "fashion", "bold"],
        imageUrl: "/images/idealPhotography-product-card-makeover-1.png",
        rating: 4.9,
        reviewCount: 78,
    },
    {
        id: "natural",
        title: "Natural Radiance",
        description: "Subtle, fresh look for everyday confidence.",
        price: 25000,
        originalPrice: 28000,
        discountPercent: 11,
        category: "casual",
        duration: "short",
        createdAt: "2024-01-18",
        tags: ["natural", "fresh", "minimal"],
        imageUrl: "/images/idealPhotography-product-card-makeover-2.png",
        rating: 4.4,
        reviewCount: 65,
    },
    {
        id: "retro",
        title: "Retro Vibes",
        description: "Vintage-inspired makeover for a timeless appearance.",
        price: 32000,
        originalPrice: 37000,
        discountPercent: 14,
        category: "retro",
        duration: "medium",
        createdAt: "2024-01-22",
        tags: ["retro", "vintage", "timeless"],
        imageUrl: "/images/idealPhotography-product-card-makeover-1.png",
        rating: 4.7,
        reviewCount: 92,
    },
];

// Enhanced photoshoot services data
export const PHOTOSHOOTS = [
    {
        id: "portrait-studio",
        title: "Studio Portrait Session",
        description: "Professional studio portraits with premium lighting setup and expert guidance.",
        price: 75000,
        originalPrice: 85000,
        discountPercent: 12,
        category: "portrait",
        duration: "2 hours",
        createdAt: "2024-01-15",
        tags: ["portrait", "studio", "professional"],
        imageUrl: "/images/idealPhotography-product-card-photoshoot-1.png",
        rating: 4.9,
        reviewCount: 156,
    },
    {
        id: "outdoor-portrait",
        title: "Outdoor Portrait Session",
        description: "Natural light portraits in beautiful outdoor locations around Lagos.",
        price: 65000,
        originalPrice: 75000,
        discountPercent: 13,
        category: "portrait",
        duration: "2 hours",
        createdAt: "2024-01-10",
        tags: ["portrait", "outdoor", "natural"],
        imageUrl: "/images/idealPhotography-product-card-photoshoot-2.png",
        rating: 4.8,
        reviewCount: 203,
    },
    {
        id: "family-session",
        title: "Family Photography",
        description: "Capture precious family moments with our family photography package.",
        price: 95000,
        originalPrice: 110000,
        discountPercent: 14,
        category: "family",
        duration: "3 hours",
        createdAt: "2024-01-20",
        tags: ["family", "portrait", "memories"],
        imageUrl: "/images/idealPhotography-product-card-photoshoot-1.png",
        rating: 4.7,
        reviewCount: 89,
    },
    {
        id: "couple-session",
        title: "Couple Photography",
        description: "Romantic couple sessions perfect for engagements, anniversaries, or just because.",
        price: 80000,
        originalPrice: 90000,
        discountPercent: 11,
        category: "couple",
        duration: "2 hours",
        createdAt: "2024-01-12",
        tags: ["couple", "romantic", "engagement"],
        imageUrl: "/images/idealPhotography-product-card-photoshoot-2.png",
        rating: 4.9,
        reviewCount: 134,
    },
    {
        id: "maternity-session",
        title: "Maternity Photography",
        description: "Beautiful maternity sessions to capture this special time in your life.",
        price: 85000,
        originalPrice: 95000,
        discountPercent: 11,
        category: "maternity",
        duration: "2 hours",
        createdAt: "2024-01-25",
        tags: ["maternity", "pregnancy", "beautiful"],
        imageUrl: "/images/idealPhotography-product-card-photoshoot-1.png",
        rating: 4.8,
        reviewCount: 67,
    },
    {
        id: "fashion-editorial",
        title: "Fashion Editorial",
        description: "High-fashion editorial shoots for models, influencers, and fashion brands.",
        price: 120000,
        originalPrice: 140000,
        discountPercent: 14,
        category: "fashion",
        duration: "4 hours",
        createdAt: "2024-01-18",
        tags: ["fashion", "editorial", "professional"],
        imageUrl: "/images/idealPhotography-product-card-photoshoot-2.png",
        rating: 4.9,
        reviewCount: 45,
    },
    {
        id: "product-photography",
        title: "Product Photography",
        description: "Professional product photography for e-commerce, catalogs, and marketing.",
        price: 60000,
        originalPrice: 70000,
        discountPercent: 14,
        category: "product",
        duration: "2 hours",
        createdAt: "2024-01-22",
        tags: ["product", "commercial", "e-commerce"],
        imageUrl: "/images/idealPhotography-product-card-photoshoot-1.png",
        rating: 4.6,
        reviewCount: 78,
    },
    {
        id: "graduation-session",
        title: "Graduation Photography",
        description: "Celebrate your academic achievement with a professional graduation photo session.",
        price: 70000,
        originalPrice: 80000,
        discountPercent: 13,
        category: "graduation",
        duration: "2 hours",
        createdAt: "2024-01-28",
        tags: ["graduation", "academic", "celebration"],
        imageUrl: "/images/idealPhotography-product-card-photoshoot-2.png",
        rating: 4.7,
        reviewCount: 112,
    },
];