// UI Strings
export const SITE_NAME = "Ideal Photography";
export const TAGLINE = "Your premier destination for professional photography equipment rentals.";

// Dummy product data for ProductList page
export const DUMMY_PRODUCTS = [
    {
        id: 1,
        title: "Canon EOS 90D DSLR Kit",
        description: "Compact and powerful DSLR kit perfect for event and portrait photography. Includes lens + carry case.",
        image: "/images/idealPhotography-product-card-equipment-1.png",
        hoverImage: "/images/idealPhotography-product-card-equipment-2.png",
        discountPercent: 17,
        price: 2499.99,
        originalPrice: 2999.99,
        stock: 12,
        rating: 4,
        reviewCount: 134,
        discountValidUntil: "July 30",
        category: "cameras",
        tags: ["dslr", "canon", "kit", "professional"],
        createdAt: "2024-01-15",
    },
    {
        id: 2,
        title: "Nikon D850",
        description: "High-resolution full-frame DSLR for professionals.",
        image: "/images/idealPhotography-product-card-equipment-2.png",
        hoverImage: "/images/idealPhotography-product-card-equipment-1.png",
        discountPercent: 10,
        price: 3499.99,
        originalPrice: 3899.99,
        stock: 7,
        rating: 5,
        reviewCount: 89,
        discountValidUntil: "Nov 30",
        category: "cameras",
        tags: ["dslr", "nikon", "full-frame", "professional"],
        createdAt: "2024-01-10",
    },
    {
        id: 3,
        title: "Photoshoot Booking",
        description: "Reserve a professional studio or outdoor photoshoot session.",
        image: "/images/idealPhotography-product-card-photoshoot-1.png",
        hoverImage: "/images/idealPhotography-product-card-photoshoot-2.png",
        discountPercent: 10,
        price: 199.99,
        originalPrice: 249.99,
        stock: 20,
        rating: 5,
        reviewCount: 42,
        discountValidUntil: "Dec 30",
        category: "services",
        tags: ["photoshoot", "studio", "outdoor", "session"],
        createdAt: "2024-01-20",
    },
    {
        id: 4,
        title: "Event Booking",
        description: "Book our team for weddings, parties, and corporate events.",
        image: "/images/idealPhotography-product-card-makeover-1.png",
        hoverImage: "/images/idealPhotography-product-card-makeover-2.png",
        discountPercent: 10,
        price: 499.99,
        originalPrice: 599.99,
        stock: 5,
        rating: 5,
        reviewCount: 27,
        discountValidUntil: "Jan 30",
        category: "services",
        tags: ["event", "wedding", "corporate", "coverage"],
        createdAt: "2024-01-25",
    },
    {
        id: 5,
        title: "Canon RF 50mm f/1.8 STM Lens",
        description: "A compact, lightweight prime lens for Canon RF-mount cameras. Perfect for portraits and low-light photography.",
        image: "/images/idealPhotography-product-card-equipment-1.png",
        hoverImage: "/images/idealPhotography-product-card-equipment-2.png",
        discountPercent: 5,
        price: 129.99,
        originalPrice: 149.99,
        stock: 15,
        rating: 4,
        reviewCount: 58,
        discountValidUntil: "Feb 30",
        category: "lenses",
        tags: ["canon", "prime", "portrait", "low-light"],
        createdAt: "2024-01-05",
    },
    {
        id: 6,
        title: "Godox AD200Pro Flash",
        description: "Portable, powerful flash for on-location shoots. TTL, HSS, and multiple light modifiers supported.",
        image: "/images/idealPhotography-product-card-equipment-2.png",
        hoverImage: "/images/idealPhotography-product-card-equipment-1.png",
        discountPercent: 8,
        price: 299.99,
        originalPrice: 324.99,
        stock: 0,
        rating: 5,
        reviewCount: 33,
        discountValidUntil: "Mar 30",
        category: "lighting",
        tags: ["flash", "godox", "ttl", "hss", "portable"],
        createdAt: "2024-01-12",
    },
    // TODO: Add more dummy products or fetch from server when available
];

// Our Services (for homepage and footer)
export const OUR_SERVICES = [
    {
        title: "Equipment Rentals",
        subtitle: "Rent cameras, lenses, lighting, and more from top and notable brands.",
        href: "/equipment",
        iconType: "camera",
        gifUrl: "/GIFs/idealPhotography-feature-card-equipment.gif",
        imageUrl: "/images/idealPhotography-feature-card-equipment.png",
    },
    {
        title: "Makeover Sessions",
        subtitle: "Book professional makeover and styling sessions.",
        href: "/makeover",
        iconType: "makeover",
        gifUrl: "/GIFs/idealPhotography-feature-card-makeover.gif",
        imageUrl: "/images/idealPhotography-feature-card-makeover.jpg",
    },
    {
        title: "Photoshoot Bookings",
        subtitle: "Reserve studio or outdoor photoshoot sessions.",
        href: "/photoshoot",
        iconType: "photoshoot",
        gifUrl: "/GIFs/idealPhotography-feature-card-photoshoot.gif",
        imageUrl: "/images/idealPhotography-feature-card-photoshoot.png",
    },
    {
        title: "Event Coverage",
        subtitle: "Hire our team for weddings, parties, and corporate events.",
        href: "/events",
        iconType: "users",
        gifUrl: "/GIFs/idealPhotography-feature-card-event.gif",
        imageUrl: "/images/idealPhotography-feature-card-event.png",
    },
    {
        title: "Mini Mart",
        subtitle: "Shop photography accessories, prints, and more.",
        href: "/mini-mart",
        iconType: "shop",
        gifUrl: "/GIFs/idealPhotography-feature-card-shop.gif",
        imageUrl: "/images/idealPhotography-feature-card-mini-shop.jpg",
    },
];

// Why Choose Us (for homepage)
export const WHY_CHOOSE_US = [
    {
        title: "Premium Equipment",
        description: "Access to the latest cameras, lenses, and accessories from top brands like Canon, Sony, Nikon, and more.",
        iconType: "camera",
    },
    {
        title: "Flexible Rental Periods",
        description: "Rent for a day, week, or month. We offer competitive rates for both short-term and long-term rentals.",
        iconType: "time",
    },
    {
        title: "Expert Support",
        description: "Our photography experts are available 24/7 to help you choose the right equipment and provide technical support.",
        iconType: "support",
    },
    {
        title: "Easy Booking",
        description: "Simple online booking system with real-time availability. Reserve your gear in just a few clicks.",
        iconType: "photoshoot",
    },
    {
        title: "Quality Guaranteed",
        description: "All equipment is professionally maintained, tested, and cleaned before every rental to ensure peak performance.",
        iconType: "quality",
    },
    {
        title: "Insured Equipment",
        description: "All rentals include comprehensive insurance coverage for peace of mind during your creative projects.",
        iconType: "secure",
    },
]; 